<?php

namespace Proxies\__CG__\CommercialAds\AdBundle\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Image extends \CommercialAds\AdBundle\Entity\Image implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function getPath1()
    {
        $this->__load();
        return parent::getPath1();
    }

    public function setPath1($path)
    {
        $this->__load();
        return parent::setPath1($path);
    }

    public function getPath2()
    {
        $this->__load();
        return parent::getPath2();
    }

    public function setPath2($path)
    {
        $this->__load();
        return parent::setPath2($path);
    }

    public function getPath3()
    {
        $this->__load();
        return parent::getPath3();
    }

    public function setPath3($path)
    {
        $this->__load();
        return parent::setPath3($path);
    }

    public function getPath4()
    {
        $this->__load();
        return parent::getPath4();
    }

    public function setPath4($path)
    {
        $this->__load();
        return parent::setPath4($path);
    }

    public function getPath5()
    {
        $this->__load();
        return parent::getPath5();
    }

    public function setPath5($path)
    {
        $this->__load();
        return parent::setPath5($path);
    }

    public function setAd(\CommercialAds\AdBundle\Entity\Ad $ad = NULL)
    {
        $this->__load();
        return parent::setAd($ad);
    }

    public function getAd()
    {
        $this->__load();
        return parent::getAd();
    }

    public function uploadImg($key, $path)
    {
        $this->__load();
        return parent::uploadImg($key, $path);
    }

    public function removeFile()
    {
        $this->__load();
        return parent::removeFile();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'path1', 'path2', 'path3', 'path4', 'path5', 'ad');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}